title: Paro 的世界
defaultContentLanguage: zh-cn
hasCJKLanguage: true
disableHugoGeneratorInject: true
baseURL: https://refparo.github.io/
disableKinds: [taxonomy, term]
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    lineNos: true
    noClasses: false
    style: solorized-dark
    tabWidth: 2
  tableOfContents:
    ordered: true
    startLevel: 2
    endLevel: 3
